### ISSUE TITLE
Network error: Unexpected token C in JSON at position 0

### ISSUE THREAD

**Issue by jhartma** [apollostack/apollo-client#1181]
I am using apollo-client@7.3 on the server to set up some testing data. Somehow I don't get it to work, seems it is not sending valid JSON data

Here is the setup:
```js
const ApolloClient = require("apollo-client").ApolloClient
const createNetworkInterface = require("apollo-client").createNetworkInterface
const fetch = require("isomorphic-fetch")

const networkInterface = createNetworkInterface({ uri: "http://localhost:4000" })

module.exports = new ApolloClient({
  networkInterface,
  ssrMode: true,
})
```

And here is how the mutation is called
```js
client.mutate({
  mutation: gql`
    mutation ($username: String, $email: String, $password: String){
      integrationTestsCreateUser(username: $username, email: $email, password: $password) { _id }
    }
  `,
  variables: {
    username: "user",
    email: "email@email.com",
    password: "password",
  },
}).then(({ data }) => {
  console.log(data)
}).catch((error) => {
  console.log(error)
})
```

Not sure what I'm doing wrong, this is the error message 
```bash
{ Error
    at new ApolloError (.../node_modules/apollo-client/apollo.umd.js:1498:23)
    at .../node_modules/apollo-client/apollo.umd.js:2269:24
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
  graphQLErrors: undefined,
  networkError: 
   SyntaxError: Unexpected token C in JSON at position 0
       at JSON.parse (<anonymous>)
       at .../node_modules/node-fetch/lib/body.js:48:15
       at process._tickDomainCallback (internal/process/next_tick.js:129:7),
  message: 'Network error: Unexpected token C in JSON at position 0',
  extraInfo: undefined }
```

**Comment by jhartma** [comment]
Uh, nevermind, the server I was calling was sitting behind a proxy and called had the wrong address
