### ISSUE TITLE
Unable to get schema's introspection 

### ISSUE THREAD

**Issue by agasvina** [apollostack/apollo-client#191]
Hi there, I try to do a simple query for schema introspection as below:
```
    query getType{
      __type(name: "Person") {
        name
        kind
        fields {
          name
          type {
              name
              kind
          }
        }
      }
    }

```

According to the GraphQL', we should be able to get the specific type using that query (i.e. 
mentioned here: http://graphql.org/docs/introspection/).  I understand that the introspection schema return for "__Type" doesn't has any arguments. 
How does the apollo-client validate if the query I send is invalid? 

Returned by the Apollo-Client:
```
    Error: Can't find field name on result object ROOT_QUERY.__type({"name":"Person"}).fields.3.type.
      at node_modules/apollo-client/data/writeToStore.js:51:23
      at Array.forEach (native)
      at writeSelectionSetToStore (node_modules/apollo-client/data/writeToStore.js:46:29)
      at writeFieldToStore (node_modules/apollo-client/data/writeToStore.js:126:9)
      at node_modules/apollo-client/data/writeToStore.js:53:13
      at Array.forEach (native)
      at writeSelectionSetToStore (node_modules/apollo-client/data/writeToStore.js:46:29)
      at node_modules/apollo-client/data/writeToStore.js:105:21
      at Array.forEach (native)
      at writeFieldToStore (node_modules/apollo-client/data/writeToStore.js:92:19)
      at node_modules/apollo-client/data/writeToStore.js:53:13
      at Array.forEach (native)
      at writeSelectionSetToStore (node_modules/apollo-client/data/writeToStore.js:46:29)
      at writeFieldToStore (node_modules/apollo-client/data/writeToStore.js:126:9)
      at node_modules/apollo-client/data/writeToStore.js:53:13
      at Array.forEach (native)
      at Object.writeSelectionSetToStore (node_modules/apollo-client/data/writeToStore.js:46:29)
      at Object.data (node_modules/apollo-client/data/store.js:18:43)
      at apolloReducer (node_modules/apollo-client/store.js:22:27)
      at combination (node_modules/apollo-client/node_modules/redux/lib/combineReducers.js:117:29)
      at dispatch (node_modules/apollo-client/node_modules/redux/lib/createStore.js:179:22)
      at Object.dispatch (node_modules/apollo-client/store.js:8:16)
      at node_modules/apollo-client/QueryManager.js:217:29
```
Thanks before.

**Comment by agasvina** [comment]
closing. this is an issue in my graphql-server
