### ISSUE TITLE
Unable to npm install on linux

### ISSUE THREAD

**Issue by mquandalle** [apollostack/apollo-client#9]
Here is the full log:

```shell
➜  apollo-client git:(master) ✗ npm install        
npm WARN package.json Dependency 'graphql' exists in both dependencies and devDependencies, using 'graphql@^0.4.17' from dependencies
npm WARN package.json Dependency 'lodash' exists in both dependencies and devDependencies, using 'lodash@^4.6.1' from dependencies
npm WARN peerDependencies The peer dependency webpack@^1.0.0 included from babel-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency eslint-plugin-react@^4.0.0 included from eslint-config-airbnb will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN optional dep failed, continuing fsevents@1.0.8
-
> apollo-client@0.0.1 prepublish /home/maxime/github/apollo-client
> npm run compile


> apollo-client@0.0.1 compile /home/maxime/github/apollo-client
> babel --presets es2015,stage-0 -d lib/ src/

ReferenceError: [BABEL] src/cacheUtils.js: Unknown option: /home/maxime/github/apollo-client/.babelrc.presets
    at Logger.error (/usr/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/logger.js:58:11)
    at OptionManager.mergeOptions (/usr/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:29)
    at OptionManager.addConfig (/usr/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/usr/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/usr/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at File.initOptions (/usr/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:147:75)
    at new File (/usr/lib/node_modules/babel/node_modules/babel-core/lib/transformation/file/index.js:137:22)
    at Pipeline.transform (/usr/lib/node_modules/babel/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Object.exports.transform (/usr/lib/node_modules/babel/lib/babel/util.js:40:22)
    at Object.exports.compile (/usr/lib/node_modules/babel/lib/babel/util.js:49:20)

npm ERR! Linux 4.3.3-040303-generic
npm ERR! argv "/home/maxime/.nvm/versions/node/v4.0.0/bin/node" "/home/maxime/.nvm/versions/node/v4.0.0/bin/npm" "run" "compile"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! apollo-client@0.0.1 compile: `babel --presets es2015,stage-0 -d lib/ src/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apollo-client@0.0.1 compile script 'babel --presets es2015,stage-0 -d lib/ src/'.
npm ERR! This is most likely a problem with the apollo-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel --presets es2015,stage-0 -d lib/ src/
npm ERR! You can get their info via:
npm ERR!     npm owner ls apollo-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/maxime/github/apollo-client/npm-debug.log

npm ERR! Linux 4.3.3-040303-generic
npm ERR! argv "/home/maxime/.nvm/versions/node/v4.0.0/bin/node" "/home/maxime/.nvm/versions/node/v4.0.0/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! apollo-client@0.0.1 prepublish: `npm run compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the apollo-client@0.0.1 prepublish script 'npm run compile'.
npm ERR! This is most likely a problem with the apollo-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile
npm ERR! You can get their info via:
npm ERR!     npm owner ls apollo-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/maxime/github/apollo-client/npm-debug.log
```

**Comment by stubailo** [comment]
Hmm, odd! Looks like some weird thing with Babel maybe? Looks like @jbaxleyiii had no trouble with development. I'll try to get a linux box tomorrow and test this out.

**Comment by mquandalle** [comment]
Not trying to influence anyone here but I was actually able to `npm install` and `npm test` the `typescript` branch. I had no success with other branches :( (I wanted to test flow on this code base).

**Comment by jbaxleyiii** [comment]
@mquandalle I bet you need to `npm i -g babel-cli` first. We can add it to the package.json if we stick with babel

**Comment by mquandalle** [comment]
Yep! Thanks @jbaxleyiii, that was it.
